#!/bin/bash
# Deface all identifiable structural images in a Freesurfer 6/7 subject directory
#
# AUTHOR : Mike Tyszka, Ph.D.
# PLACE  : Caltech
# DATES  : 2020-04-01 JMT From scratch
#          2023-09-29 JMT Switch to voxface for defacing
#
# Full list of mgz images generated by FS 6/7 recon-all in <subj_dir>/mri
#
# Identifiable and in the same space
# ----
# T1.mgz
# [T2.mgz]
# nu.mgz
# orig.mgz
# orig_nu.mgz
# rawavg.mgz
#
# Identifiable and in separate spaces
# orig/*.mgz
#
# Deidentified
# ----
# aparc+aseg.mgz
# aparc.DKTatlas+aseg.mgz
# aparc.a2009s+aseg.mgz
# aseg.auto.mgz
# aseg.auto_noCCseg.mgz
# aseg.mgz
# aseg.presurf.hypos.mgz
# aseg.presurf.mgz
# brain.finalsurfs.mgz
# brain.mgz
# brainmask.auto.mgz
# brainmask.mgz
# ctrl_pts.mgz
# filled.mgz
# lh.ribbon.mgz
# norm.mgz
# rh.ribbon.mgz
# ribbon.mgz
# wm.asegedit.mgz
# wm.mgz
# wm.seg.mgz
# wmparc.mgz

# FS subject recon directory
if [ $# -lt 1 ]
then
  echo "USAGE : fs_deface.sh <Freesurfer 6/7 subject recon folder>"
  exit
else
  subj_dir=$1
fi

echo ""
echo "----"
echo "Deface Freesurfer recon data in ${subj_dir}"
echo "----"

subj_id=$(basename ${subj_dir})

# All identifiable images are in <subj_dir>/mri
mri_dir=${subj_dir}/mri

# Convert everything that needs defacing to nii.gz
for mgz_fname in ${mri_dir}/T?.mgz ${mri_dir}/nu.mgz ${mri_dir}/orig*mgz ${mri_dir}/rawavg.mgz ${mri_dir}/orig/*.mgz
do

  echo ""
  echo "$(basename ${mgz_fname})"

  nii_fname=${mgz_fname/.mgz/.nii.gz}
  bak_fname=${mgz_fname/.mgz/.mgz.bak}
  defac_fname=${nii_fname/.nii.gz/_defaced.nii.gz}

  # Backup original image
  echo "  Backing up"
  cp ${mgz_fname} ${bak_fname}

  echo "  Converting faced image from .mgz to .nii.gz"
  mri_convert ${mgz_fname} ${nii_fname} > /dev/null

  echo "  Defacing .nii.gz"
  voxface -i ${nii_fname}

  echo "  Copying defaced .nii.gz to .mgz"
  mri_convert ${defac_fname} ${mgz_fname} > /dev/null

  # Cleanup .nii.gz images
  echo "  Cleaning up .nii.gz images"
  rm -rf ${nii_fname} ${defac_fname}

done
